"""Add new fields to User model: favorite_genres, favorite_instrument, job, twitter, facebook, instagram

Revision ID: 14bf8a0c47e0
Revises: 
Create Date: 2024-01-26 19:41:07.933271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14bf8a0c47e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('twitter', sa.String(length=255), nullable=True))
    op.add_column('user_info', sa.Column('facebook', sa.String(length=255), nullable=True))
    op.add_column('user_info', sa.Column('instagram', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'instagram')
    op.drop_column('user_info', 'facebook')
    op.drop_column('user_info', 'twitter')
    # ### end Alembic commands ###
