"""Initial migration

Revision ID: e26fc6ace091
Revises: 
Create Date: 2024-01-22 13:35:17.432407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e26fc6ace091'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('UserInfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_genres', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('favorite_instrument', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('job', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_column('mobile')
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserInfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('mobile', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('job')
        batch_op.drop_column('favorite_instrument')
        batch_op.drop_column('favorite_genres')

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
